const CURRICULUM = [
  {
    id: 'foundation',
    label: 'Foundation',
    color: '#7c3aed',
    topics: [
      {
        id: 'f_count_forward',
        label: 'Counting Forward to 20',
        type: 'sequence',
        config: { mode: 'forward', step: 1, minStart: 1, maxStart: 10, length: 8 },
        defaultCount: 15,
      },
      {
        id: 'f_count_backward',
        label: 'Counting Backward from 20',
        type: 'sequence',
        config: { mode: 'backward', step: 1, minStart: 10, maxStart: 20, length: 8 },
        defaultCount: 15,
      },
      {
        id: 'f_number_bonds_10',
        label: 'Number Bonds to 10',
        type: 'numberBonds',
        config: { total: 10 },
        defaultCount: 20,
      },
      {
        id: 'f_add_to10',
        label: 'Addition to 10',
        type: 'arithmetic',
        config: { operations: ['+'], minOperand: 1, maxOperand: 5 },
        defaultCount: 20,
      },
      {
        id: 'f_sub_from10',
        label: 'Subtraction from 10',
        type: 'arithmetic',
        config: { operations: ['-'], minOperand: 1, maxOperand: 10 },
        defaultCount: 20,
      },
    ],
  },

  {
    id: 'year1',
    label: 'Year 1',
    color: '#6d28d9',
    topics: [
      {
        id: 'y1_skip_2',
        label: 'Skip Counting by 2s',
        type: 'sequence',
        config: { step: 2, minStart: 2, maxStart: 10, length: 6 },
        defaultCount: 15,
      },
      {
        id: 'y1_skip_5',
        label: 'Skip Counting by 5s',
        type: 'sequence',
        config: { step: 5, minStart: 5, maxStart: 30, length: 6 },
        defaultCount: 15,
      },
      {
        id: 'y1_skip_10',
        label: 'Skip Counting by 10s',
        type: 'sequence',
        config: { step: 10, minStart: 10, maxStart: 50, length: 6 },
        defaultCount: 15,
      },
      {
        id: 'y1_add_20',
        label: 'Addition to 20',
        type: 'arithmetic',
        config: { operations: ['+'], minOperand: 1, maxOperand: 10 },
        defaultCount: 20,
      },
      {
        id: 'y1_sub_20',
        label: 'Subtraction to 20',
        type: 'arithmetic',
        config: { operations: ['-'], minOperand: 1, maxOperand: 20 },
        defaultCount: 20,
      },
      {
        id: 'y1_bonds_20',
        label: 'Number Bonds to 20',
        type: 'numberBonds',
        config: { total: 20 },
        defaultCount: 20,
      },
      {
        id: 'y1_halves_quarters',
        label: 'Halves and Quarters',
        type: 'fractionOfGroup',
        config: { denominators: [2, 4], maxWhole: 20 },
        defaultCount: 15,
      },
    ],
  },

  {
    id: 'year2',
    label: 'Year 2',
    color: '#1d4ed8',
    topics: [
      {
        id: 'y2_place_value',
        label: 'Place Value to 1 000',
        type: 'placeValue',
        config: { digits: 3 },
        defaultCount: 20,
      },
      {
        id: 'y2_skip_3',
        label: 'Skip Counting by 3s',
        type: 'sequence',
        config: { step: 3, minStart: 3, maxStart: 15, length: 6 },
        defaultCount: 15,
      },
      {
        id: 'y2_skip_4',
        label: 'Skip Counting by 4s',
        type: 'sequence',
        config: { step: 4, minStart: 4, maxStart: 20, length: 6 },
        defaultCount: 15,
      },
      {
        id: 'y2_add_100',
        label: 'Addition to 100',
        type: 'arithmetic',
        config: { operations: ['+'], minOperand: 1, maxOperand: 50 },
        defaultCount: 20,
      },
      {
        id: 'y2_sub_100',
        label: 'Subtraction to 100',
        type: 'arithmetic',
        config: { operations: ['-'], minOperand: 1, maxOperand: 100 },
        defaultCount: 20,
      },
      {
        id: 'y2_tables_2_5_10',
        label: 'Tables: 2×, 5×, 10×',
        type: 'arithmetic',
        config: { operations: ['×'], minOperand: 1, maxOperand: 10, restrictTables: [2, 5, 10] },
        defaultCount: 20,
      },
      {
        id: 'y2_fractions_basic',
        label: 'Fractions: Halves, Quarters, Eighths',
        type: 'fractionOfGroup',
        config: { denominators: [2, 4, 8], maxWhole: 24 },
        defaultCount: 15,
      },
      {
        id: 'y2_money',
        label: 'Money: Adding and Subtracting',
        type: 'money',
        config: { maxAmount: 10 },
        defaultCount: 15,
      },
      {
        id: 'y2_shapes',
        label: '2D Shape Properties',
        type: 'shapeProperties',
        config: { level: 1 },
        defaultCount: 16,
      },
    ],
  },

  {
    id: 'year3',
    label: 'Year 3',
    color: '#0369a1',
    topics: [
      {
        id: 'y3_place_value',
        label: 'Place Value to 10 000',
        type: 'placeValue',
        config: { digits: 4 },
        defaultCount: 20,
      },
      {
        id: 'y3_rounding',
        label: 'Rounding to Nearest 10 and 100',
        type: 'rounding',
        config: { minValue: 10, maxValue: 999, roundTo: [10, 100] },
        defaultCount: 20,
      },
      {
        id: 'y3_add_3digit',
        label: 'Adding 3-Digit Numbers',
        type: 'arithmetic',
        config: { operations: ['+'], minOperand: 100, maxOperand: 999 },
        defaultCount: 16,
      },
      {
        id: 'y3_sub_3digit',
        label: 'Subtracting 3-Digit Numbers',
        type: 'arithmetic',
        config: { operations: ['-'], minOperand: 100, maxOperand: 999 },
        defaultCount: 16,
      },
      {
        id: 'y3_tables_2_6_10',
        label: 'Multiplication Tables: 2–6 and 10',
        type: 'arithmetic',
        config: { operations: ['×'], minOperand: 1, maxOperand: 10, restrictTables: [2, 3, 4, 5, 6, 10] },
        defaultCount: 20,
      },
      {
        id: 'y3_division',
        label: 'Division Facts',
        type: 'arithmetic',
        config: { operations: ['÷'], minOperand: 2, maxOperand: 10 },
        defaultCount: 20,
      },
      {
        id: 'y3_fractions_thirds',
        label: 'Fractions: Thirds and Sixths',
        type: 'fractionOfGroup',
        config: { denominators: [3, 6], maxWhole: 18 },
        defaultCount: 15,
      },
      {
        id: 'y3_perimeter',
        label: 'Perimeter of Rectangles',
        type: 'perimeter',
        config: { minSide: 2, maxSide: 15 },
        defaultCount: 15,
      },
      {
        id: 'y3_symmetry',
        label: 'Lines of Symmetry',
        type: 'shapeProperties',
        config: { level: 2 },
        defaultCount: 16,
      },
    ],
  },

  {
    id: 'year4',
    label: 'Year 4',
    color: '#047857',
    topics: [
      {
        id: 'y4_place_value',
        label: 'Place Value to 100 000',
        type: 'placeValue',
        config: { digits: 5 },
        defaultCount: 20,
      },
      {
        id: 'y4_rounding',
        label: 'Rounding to Nearest 1 000',
        type: 'rounding',
        config: { minValue: 1000, maxValue: 99999, roundTo: [1000] },
        defaultCount: 20,
      },
      {
        id: 'y4_add_large',
        label: 'Adding Large Numbers',
        type: 'arithmetic',
        config: { operations: ['+'], minOperand: 1000, maxOperand: 9999 },
        defaultCount: 16,
      },
      {
        id: 'y4_sub_large',
        label: 'Subtracting Large Numbers',
        type: 'arithmetic',
        config: { operations: ['-'], minOperand: 1000, maxOperand: 9999 },
        defaultCount: 16,
      },
      {
        id: 'y4_tables_7_9',
        label: 'Multiplication Tables: 7, 8, 9',
        type: 'arithmetic',
        config: { operations: ['×'], minOperand: 1, maxOperand: 12, restrictTables: [7, 8, 9] },
        defaultCount: 20,
      },
      {
        id: 'y4_mult_2x1',
        label: '2-Digit × 1-Digit Multiplication',
        type: 'arithmetic',
        config: { operations: ['×'], minOperand: 2, maxOperand: 9, minOperandA: 10, maxOperandA: 99 },
        defaultCount: 20,
      },
      {
        id: 'y4_div_remainder',
        label: 'Division with Remainders',
        type: 'divisionRemainder',
        config: { minDivisor: 2, maxDivisor: 9, minDividend: 10, maxDividend: 99 },
        defaultCount: 20,
      },
      {
        id: 'y4_equiv_fractions',
        label: 'Equivalent Fractions',
        type: 'equivFractions',
        config: { maxDenom: 12 },
        defaultCount: 20,
      },
      {
        id: 'y4_frac_add_same',
        label: 'Adding Fractions (Same Denominator)',
        type: 'fractionArithmetic',
        config: { operation: '+', sameDenom: true, maxDenom: 12 },
        defaultCount: 20,
      },
      {
        id: 'y4_frac_sub_same',
        label: 'Subtracting Fractions (Same Denominator)',
        type: 'fractionArithmetic',
        config: { operation: '-', sameDenom: true, maxDenom: 12 },
        defaultCount: 20,
      },
      {
        id: 'y4_decimal_tenths',
        label: 'Decimal Tenths',
        type: 'decimalArithmetic',
        config: { decimalPlaces: 1, operation: '+-', maxValue: 9.9 },
        defaultCount: 20,
      },
      {
        id: 'y4_decimal_hundredths',
        label: 'Decimal Hundredths',
        type: 'decimalArithmetic',
        config: { decimalPlaces: 2, operation: '+-', maxValue: 9.99 },
        defaultCount: 20,
      },
      {
        id: 'y4_area',
        label: 'Area of Rectangles',
        type: 'area',
        config: { shape: 'rectangle', minSide: 2, maxSide: 12 },
        defaultCount: 15,
      },
      {
        id: 'y4_perimeter',
        label: 'Perimeter of Rectangles',
        type: 'perimeter',
        config: { minSide: 2, maxSide: 20 },
        defaultCount: 15,
      },
      {
        id: 'y4_angles_naming',
        label: 'Naming Angles',
        type: 'angles',
        config: { mode: 'name' },
        defaultCount: 20,
      },
    ],
  },

  {
    id: 'year5',
    label: 'Year 5',
    color: '#b45309',
    topics: [
      {
        id: 'y5_prime_composite',
        label: 'Prime and Composite Numbers',
        type: 'primeComposite',
        config: { min: 2, max: 50 },
        defaultCount: 20,
      },
      {
        id: 'y5_factors',
        label: 'Factors and Multiples',
        type: 'factors',
        config: { min: 2, max: 50 },
        defaultCount: 15,
      },
      {
        id: 'y5_order_ops',
        label: 'Order of Operations (BODMAS)',
        type: 'orderOfOps',
        config: { level: 1 },
        defaultCount: 15,
      },
      {
        id: 'y5_mult_2x2',
        label: '2-Digit × 2-Digit Multiplication',
        type: 'arithmetic',
        config: { operations: ['×'], minOperand: 10, maxOperand: 99 },
        defaultCount: 16,
      },
      {
        id: 'y5_long_division',
        label: 'Long Division',
        type: 'arithmetic',
        config: { operations: ['LD'] },
        defaultCount: 12,
      },
      {
        id: 'y5_improper_mixed',
        label: 'Improper Fractions and Mixed Numbers',
        type: 'improperMixed',
        config: { maxDenom: 8, maxWhole: 5 },
        defaultCount: 20,
      },
      {
        id: 'y5_frac_add_diff',
        label: 'Adding Fractions (Different Denominators)',
        type: 'fractionArithmetic',
        config: { operation: '+', sameDenom: false, maxDenom: 10 },
        defaultCount: 20,
      },
      {
        id: 'y5_frac_sub_diff',
        label: 'Subtracting Fractions (Different Denominators)',
        type: 'fractionArithmetic',
        config: { operation: '-', sameDenom: false, maxDenom: 10 },
        defaultCount: 20,
      },
      {
        id: 'y5_frac_mult_whole',
        label: 'Fractions × Whole Numbers',
        type: 'fractionMultiply',
        config: { maxDenom: 8, maxWhole: 6 },
        defaultCount: 20,
      },
      {
        id: 'y5_decimal_add_sub',
        label: 'Adding and Subtracting Decimals',
        type: 'decimalArithmetic',
        config: { decimalPlaces: 2, operation: '+-', maxValue: 99.99 },
        defaultCount: 20,
      },
      {
        id: 'y5_percentages',
        label: 'Percentages of Quantities',
        type: 'percentage',
        config: { level: 1 },
        defaultCount: 15,
      },
      {
        id: 'y5_convert_frac_dec_pct',
        label: 'Converting Fractions, Decimals, Percentages',
        type: 'fracDecPct',
        config: {},
        defaultCount: 20,
      },
      {
        id: 'y5_angles_missing',
        label: 'Missing Angles (Line and Point)',
        type: 'angles',
        config: { mode: 'missing-line' },
        defaultCount: 20,
      },
      {
        id: 'y5_coordinates',
        label: 'Coordinates (First Quadrant)',
        type: 'coordinates',
        config: { mode: 'read', maxCoord: 10 },
        defaultCount: 15,
      },
    ],
  },

  {
    id: 'year6',
    label: 'Year 6',
    color: '#b91c1c',
    topics: [
      {
        id: 'y6_frac_mult',
        label: 'Multiplying Fractions',
        type: 'fractionArithmetic',
        config: { operation: '×', maxDenom: 8 },
        defaultCount: 20,
      },
      {
        id: 'y6_frac_div',
        label: 'Dividing Fractions by Whole Numbers',
        type: 'fractionDivide',
        config: { maxDenom: 8, maxWhole: 6 },
        defaultCount: 20,
      },
      {
        id: 'y6_decimal_mult',
        label: 'Multiplying Decimals',
        type: 'decimalArithmetic',
        config: { decimalPlaces: 2, operation: '×', maxValue: 9.99 },
        defaultCount: 20,
      },
      {
        id: 'y6_percentages',
        label: 'Percentages of Quantities',
        type: 'percentage',
        config: { level: 2 },
        defaultCount: 15,
      },
      {
        id: 'y6_ratios',
        label: 'Ratios and Rates',
        type: 'ratio',
        config: { maxValue: 12 },
        defaultCount: 15,
      },
      {
        id: 'y6_order_ops',
        label: 'Order of Operations (Brackets and Powers)',
        type: 'orderOfOps',
        config: { level: 2 },
        defaultCount: 15,
      },
      {
        id: 'y6_negative',
        label: 'Negative Numbers',
        type: 'negativeNumbers',
        config: { min: -10, max: 10 },
        defaultCount: 20,
      },
      {
        id: 'y6_algebra_sub',
        label: 'Algebra: Substitution',
        type: 'algebraSubstitution',
        config: { maxCoeff: 5, maxConst: 10, maxValue: 6 },
        defaultCount: 15,
      },
      {
        id: 'y6_equations',
        label: 'Simple Equations',
        type: 'simpleEquations',
        config: { maxCoeff: 5, maxAnswer: 10 },
        defaultCount: 15,
      },
      {
        id: 'y6_area_triangle',
        label: 'Area of Triangles',
        type: 'area',
        config: { shape: 'triangle', minSide: 2, maxSide: 15 },
        defaultCount: 15,
      },
      {
        id: 'y6_volume',
        label: 'Volume of Rectangular Prisms',
        type: 'volume',
        config: { minSide: 2, maxSide: 10 },
        defaultCount: 15,
      },
      {
        id: 'y6_statistics',
        label: 'Mean, Median, Mode and Range',
        type: 'statistics',
        config: { setSize: 6, minValue: 1, maxValue: 20 },
        defaultCount: 10,
      },
      {
        id: 'y6_angles_shapes',
        label: 'Angles in Triangles and Quadrilaterals',
        type: 'angles',
        config: { mode: 'missing-shape' },
        defaultCount: 20,
      },
      {
        id: 'y6_coordinates',
        label: 'Coordinates and Transformations',
        type: 'coordinates',
        config: { mode: 'transform', maxCoord: 8 },
        defaultCount: 15,
      },
    ],
  },
];
